//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 電力計算
    /// </summary>
    public class Elec_properties
    {
        /// <summary>
        /// 年份
        /// </summary>
        [Key]
        [Display(Name = "年份")] 
        public string year { get; set; }

        /// <summary>
        /// 排放源名稱
        /// </summary>
        [Display(Name = "排放源名稱")]
        public string Name { get; set; }

        /// <summary>
        /// 燃料單位
        /// </summary>
        [Display(Name = "燃料單位")]
        public string Unit { get; set; }

        /// <summary>
        /// 二氧化碳排放係數
        /// </summary>
        [Display(Name = "二氧化碳排放係數*GWP")]
        public decimal Co2e { get; set; }

        /// <summary>
        /// 最小單位數
        /// </summary>
        [Display(Name = "最小單位數")]
        public float MinValue { get; set; }

        /// <summary>
        /// 最大單位數
        /// </summary>
        [Display(Name = "最大單位數")]
        public float MaxValue { get; set; }
    }
}
