//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using Dou.Misc.Attr;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    /// <summary>
    /// 燃料計算
    /// </summary>
    public partial class Escape_properties
    {
        /// <summary>
        /// 編號
        /// </summary>
        [Key]
        [Display(Name = "編號")]
        public string Id { get; set; }

        /// <summary>
        /// 排放源類別
        /// </summary>
        [Display(Name = "排放源類別")]
        [ColumnDef(VisibleView = false, VisibleEdit = true, EditType = EditType.Select,
            SelectSourceDbContextNamespace = "CFC.Models.DouModelContext, CFC",
            SelectSourceModelNamespace = "CFC.Models.Prj.Escape_type, CFC",
            SelectSourceModelValueField = "Id",
            SelectSourceModelDisplayField = "Name")]

        public string Type { get; set; }
        [Display(Name = "排放源類別")]

        [NotMapped]
        [ColumnDef(VisibleView = true, VisibleEdit = false)]
        public string TypeName
        {
            get
            {
                var selectedType = Controllers.Api.DateViewController.AllEscapeType.Where(e => e.Id == this.Type).FirstOrDefault();
                if (selectedType == null)
                    return "無對應逸散種類";
                else
                    return selectedType.Name;
            }
            set { }
        }

        /// <summary>
        /// 排放源名稱
        /// </summary>
        [Display(Name = "排放源名稱")]
        public string Name { get; set; }

        /// <summary>
        /// 單位
        /// </summary>
        [Display(Name = "單位")]
        public string Unit { get; set; }

        [NotMapped]
        public decimal Co2e
        {
            get
            {
                return this.CO2 * Convert.ToDecimal(this.CO2GWP) +
                    this.N2O * Convert.ToDecimal(this.N2OGWP) +
                    this.CH4 * Convert.ToDecimal(this.CH4GWP) +
                    this.NF3 * Convert.ToDecimal(this.NF3GWP) +
                    this.HFCs * Convert.ToDecimal(this.HFCsGWP) +
                    this.PFCs * Convert.ToDecimal(this.PFCsGWP) +
                    this.SF6 * Convert.ToDecimal(this.SF6GWP);
            }
        }

        public decimal Co2e_AR4
        {
            get
            {
                return this.CO2 * Convert.ToDecimal(this.CO2GWP) +
                    this.N2O * Convert.ToDecimal(this.N2OGWP) +
                    this.CH4 * Convert.ToDecimal(this.CH4GWP) +
                    this.NF3 * Convert.ToDecimal(this.NF3GWP) +
                    this.HFCs * Convert.ToDecimal(this.HFCsGWP) +
                    this.PFCs * Convert.ToDecimal(this.PFCsGWP) +
                    this.SF6 * Convert.ToDecimal(this.SF6GWP);
            }
        }

        public decimal Co2e_AR5
        {
            get
            {
                return this.CO2 * Convert.ToDecimal(this.CO2GWP_AR5) +
                    this.N2O * Convert.ToDecimal(this.N2OGWP_AR5) +
                    this.CH4 * Convert.ToDecimal(this.CH4GWP_AR5) +
                    this.NF3 * Convert.ToDecimal(this.NF3GWP_AR5) +
                    this.HFCs * Convert.ToDecimal(this.HFCsGWP_AR5) +
                    this.PFCs * Convert.ToDecimal(this.PFCsGWP_AR5) +
                    this.SF6 * Convert.ToDecimal(this.SF6GWP_AR5);
            }
        }

        public decimal Co2e_AR6
        {
            get
            {
                return this.CO2 * Convert.ToDecimal(this.CO2GWP_AR6) +
                    this.N2O * Convert.ToDecimal(this.N2OGWP_AR6) +
                    this.CH4 * Convert.ToDecimal(this.CH4GWP_AR6) +
                    this.NF3 * Convert.ToDecimal(this.NF3GWP_AR6) +
                    this.HFCs * Convert.ToDecimal(this.HFCsGWP_AR6) +
                    this.PFCs * Convert.ToDecimal(this.PFCsGWP_AR6) +
                    this.SF6 * Convert.ToDecimal(this.SF6GWP_AR6);
            }
        }

        /// <summary>
        /// 二氧化碳排放係數
        /// </summary>
        [Display(Name = "二氧化碳排放係數")]
        public decimal CO2 { get; set; }

        [Display(Name = "甲浣排放係數")]
        public decimal CH4 { get; set; }

        [Display(Name = "化氮排放係數")]
        public decimal N2O { get; set; }

        [Display(Name = "氫氟(HFCs)排放係數")]
        public decimal HFCs { get; set; }

        [Display(Name = "全氟(PFCS)排放係數")]
        public decimal PFCs { get; set; }

        [Display(Name = "六氟化硫(SF6)排放係數")]
        public decimal SF6 { get; set; }
        [Display(Name = "三氟化氮(NF3)排放係數")]
        public decimal NF3 { get; set; }


        [Display(Name = "二氧化碳GWP")]
        public double CO2GWP { get; set; }

        [Display(Name = "甲浣GWP")]
        public double CH4GWP { get; set; }

        [Display(Name = "化氮GWP")]
        public double N2OGWP { get; set; }

        [Display(Name = "氫氟(HFCs)GWP")]
        public double HFCsGWP { get; set; }

        [Display(Name = "全氟(PFCS)GWP")]
        public double PFCsGWP { get; set; }

        [Display(Name = "六氟化硫(SF6)GWP")]
        public double SF6GWP { get; set; }

        [Display(Name = "三氟化氮(NF3)GWP")]
        public double NF3GWP { get; set; }



        [Display(Name = "二氧化碳GWP_AR5")]
        public double CO2GWP_AR5 { get; set; }

        [Display(Name = "甲浣GWP_AR5")]
        public double CH4GWP_AR5 { get; set; }

        [Display(Name = "化氮GWP_AR5")]
        public double N2OGWP_AR5 { get; set; }

        [Display(Name = "氫氟(HFCs)GWP_AR5")]
        public double HFCsGWP_AR5 { get; set; }

        [Display(Name = "全氟(PFCS)GWP_AR5")]
        public double PFCsGWP_AR5 { get; set; }

        [Display(Name = "六氟化硫(SF6)GWP_AR5")]
        public double SF6GWP_AR5 { get; set; }

        [Display(Name = "三氟化氮(NF3)GWP_AR5")]
        public double NF3GWP_AR5 { get; set; }



        [Display(Name = "二氧化碳GWP_AR6")]
        public double CO2GWP_AR6 { get; set; }

        [Display(Name = "甲浣GWP_AR6")]
        public double CH4GWP_AR6 { get; set; }

        [Display(Name = "化氮GWP_AR6")]
        public double N2OGWP_AR6 { get; set; }

        [Display(Name = "氫氟(HFCs)GWP_AR6")]
        public double HFCsGWP_AR6 { get; set; }

        [Display(Name = "全氟(PFCS)GWP_AR6")]
        public double PFCsGWP_AR6 { get; set; }

        [Display(Name = "六氟化硫(SF6)GWP_AR6")]
        public double SF6GWP_AR6 { get; set; }

        [Display(Name = "三氟化氮(NF3)GWP_AR6")]
        public double NF3GWP_AR6 { get; set; }


        /// <summary>
        /// 順序
        /// </summary>
        [Display(Name = "順序")]
        public int displayOrder { get; set; }

        [Display(Name = "係數來源")]
        public string CoeSource { get; set; }


    }
}
