//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 冷媒種類
    /// </summary>
    public partial class Fuel_volume
    {
        /// <summary>
        /// 資料行的ID
        /// </summary>
        [Key]
        [Column(Order = 1)]
        [Display(Name = "資料行的ID")]
        public int RowId { get; set; }

        /// <summary>
        /// 其他逸散排放ID
        /// </summary>
        [Key]
        [Column(Order = 2)]
        [Display(Name = "燃料ID")]
        public string FuelId { get; set; }

        /// <summary>
        /// 使用量
        /// </summary>
        [Display(Name = "使用量")]
        public double UseVolume { get; set; }

        /// <summary>
        /// 其他 - 原料名稱
        /// </summary>
        [Display(Name = "其他-原料名稱")]
        public String OtherName { get; set; }

        /// <summary>
        /// 其他 - 原料係數
        /// </summary>
        [Display(Name = "其他-原料係數")]
        public decimal? OtherCoe { get; set; }

    }
}
