//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using Dou.Misc.Attr;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 燃料計算
    /// </summary>
    public partial class Fuel_properties
    {
        /// <summary>
        /// 編號
        /// </summary>
        [Key]
        [Display(Name = "編號")]
        public string Id { get; set; }

        /// <summary>
        /// 排放源類別
        /// </summary>
        [Display(Name = "排放源類別")]
        [ColumnDef(Filter = true, EditType = EditType.Select, SelectItems = "{'solid':'固態燃料', 'staticFluid':'液態固定源', 'dynamicFluid':'液態移動源', 'gas':'氣態'}")]
        public string FuelType { get; set; }

        /// <summary>
        /// 排放源名稱
        /// </summary>
        [Display(Name = "排放源名稱")]
        public string Name { get; set; }

        /// <summary>
        /// 燃料單位
        /// </summary>
        [Display(Name = "燃料單位")]
        public string Unit { get; set; }

        /// <summary>
        /// 二氧化碳排放係數
        /// </summary>
        [NotMapped]
        [Display(Name = "暫時計算用細數")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public decimal Co2e
        {
            get { return CO2GWP * CO2 + CH4 * CH4GWP + NO2 * N2OGWP; }

        }

        public decimal Co2e_AR4
        {
            get { return GCO2R4 * CO2 + GCH4R4 * CH4 + GNO2R4 * NO2; }
        }

        public decimal Co2e_AR5
        {
            get { return GCO2R5 * CO2 + GCH4R5 * CH4 + GNO2R5 * NO2; }
        }

        public decimal Co2e_AR6
        {
            get { return GCO2R6 * CO2 + GCH4R6 * CH4 + GNO2R6 * NO2; }
        }


        [Display(Name = "二氧化碳係數")]
        public decimal CO2 { get; set; }

        [Display(Name = "甲烷係數")]
        public decimal CH4 { get; set; }

        [Display(Name = "氧化亞氮係數")]
        public decimal NO2 { get; set; }

        [NotMapped]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public RType? ARType { get; set; }

        [NotMapped]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public decimal CO2GWP
        {
            get
            {
                switch (this.ARType)
                {
                    case RType.AR4:
                        return this.GCO2R4;
                    case RType.AR5:
                        return this.GCO2R5;
                    case RType.AR6:
                        return this.GCO2R6;
                    default:
                        return this.GCO2R4;
                }
            }
        }

        [NotMapped]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public decimal CH4GWP
        {
            get
            {
                switch (this.ARType)
                {
                    case RType.AR4:
                        return this.GCH4R4;
                    case RType.AR5:
                        return this.GCH4R5;
                    case RType.AR6:
                        return this.GCH4R6;
                    default:
                        return this.GCH4R4;
                }
            }
        }

        [NotMapped]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public decimal N2OGWP
        {
            get
            {
                switch (this.ARType)
                {
                    case RType.AR4:
                        return this.GNO2R4;
                    case RType.AR5:
                        return this.GNO2R5;
                    case RType.AR6:
                        return this.GNO2R6;
                    default:
                        return this.GNO2R4;
                }
            }
        }


        #region AR4
        [Display(Name = "AR4-CO2-GWP")]
        public decimal GCO2R4 { get; set; }

        [Display(Name = "AR4-CH4-GWP")]
        public decimal GCH4R4 { get; set; }

        [Display(Name = "AR4-NO2-GWP")]
        public decimal GNO2R4 { get; set; }
        #endregion


        #region AR5
        [Display(Name = "AR5-CO2-GWP")]
        public decimal GCO2R5 { get; set; }

        [Display(Name = "AR5-CH4-GWP")]
        public decimal GCH4R5 { get; set; }

        [Display(Name = "AR5-NO2-GWP")]
        public decimal GNO2R5 { get; set; }
        #endregion

        #region AR6
        [Display(Name = "AR6-CO2-GWP")]
        public decimal GCO2R6 { get; set; }

        [Display(Name = "AR6-CH4-GWP")]
        public decimal GCH4R6 { get; set; }

        [Display(Name = "AR6-NO2-GWP")]
        public decimal GNO2R6 { get; set; }
        #endregion



        /// <summary>
        /// 最小單位數
        /// </summary>
        [Display(Name = "最小單位數")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public float MinValue { get; set; }

        /// <summary>
        /// 最大單位數
        /// </summary>
        [Display(Name = "最大單位數")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public float MaxValue { get; set; }

        /// <summary>
        /// 順序
        /// </summary>
        [Display(Name = "順序")]
        public int displayOrder { get; set; }
    }

    public enum RType
    {
        AR4, AR5, AR6
    }
}
