//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using Dou.Misc.Attr;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// 燃料計算
    /// </summary>
    public partial class Global_Industrial : GlobalBase
    {
        /// <summary>
        /// 編號
        /// </summary>
        [Key]
        [Display(Name = "行業別編號")]
        public override string Id { get; set; }
    }

    public class GlobalBase
    {
        /// <summary>
        /// 編號
        /// </summary>
        public virtual string Id { get; set; }

        /// <summary>
        /// 顯示名稱\
        /// </summary>
        [Display(Name = "顯示名稱")]
        public string Name { get; set; }

        [Display(Name = "顯示順序")]
        public int DisplayOrder { get; set; }
    }
}
