//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using Dou.Misc.Attr;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    /// <summary>
    /// 工業區
    /// </summary>
    public partial class Global_IndustrialArea : GlobalBase
    {
        /// <summary>
        /// 編號
        /// </summary>
        [Key]
        [Display(Name = "工業園區")]
        public override string Id { get; set; }

        [Display(Name = "縣市")]
        public string CityName { get; set; }
    }

    public class Global_IndustrialAreaSelectItems : Dou.Misc.Attr.SelectItemsClass
    {
        public const string AssemblyQualifiedName = "CFC.Models.Prj.Global_IndustrialAreaSelectItems, CFC";

        protected static IEnumerable<Global_IndustrialArea> _globalIndustrialAreaItems;
        internal static IEnumerable<Global_IndustrialArea> GlobalIndustrialAreaItems
        {
            get
            {
                if (_globalIndustrialAreaItems == null)
                {
                    using (var db = new DouModelContext())
                    {
                        _globalIndustrialAreaItems = db.GlobalIndustrialArea
                                            .OrderBy(a => a.CityName).ThenBy(a => a.DisplayOrder)
                                            .ToArray();
                    }
                }
                return _globalIndustrialAreaItems;
            }
        }


        public static void Reset()
        {
            _globalIndustrialAreaItems = null;
        }
        public override IEnumerable<KeyValuePair<string, object>> GetSelectItems()
        {
            return GlobalIndustrialAreaItems.Select(s => new KeyValuePair<string, object>(s.Id, s.Name));
        }
    }
}
