//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using Dou.Misc.Attr;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    /// <summary>
    /// 產業別
    /// </summary>
    public partial class Global_Industrial : GlobalBase
    {
        /// <summary>
        /// 編號
        /// </summary>
        [Key]
        [Display(Name = "行業別編號")]
        public override string Id { get; set; }

        static object lockGetAllDatas = new object();

        /// <summary>
        /// 特殊 是否製造業(1否,其它全是)
        /// </summary>
        /// <param name="cachetimer"></param>
        /// <returns></returns>
        public static IEnumerable<Global_Industrial> GetAllDatasYN(int cachetimer = 0)
        {
            var allData = User_Properties_Advance.GetAllDatas().Select(a => new Global_Industrial
            {
                Id = a.IndustrialTypeId,
                Name = a.IndustrialTypeId == "1" ? "非製造業" : "製造業",
            });

            return allData;
        }
    }

    public class GlobalBase
    {
        /// <summary>
        /// 編號
        /// </summary>
        public virtual string Id { get; set; }

        /// <summary>
        /// 顯示名稱\
        /// </summary>
        [Display(Name = "顯示名稱")]
        public string Name { get; set; }

        [Display(Name = "顯示順序")]
        public int DisplayOrder { get; set; }
    }

    public class Global_IndustrialSelectItems : Dou.Misc.Attr.SelectItemsClass
    {
        public const string AssemblyQualifiedName = "CFC.Models.Prj.Global_IndustrialSelectItems, CFC";

        protected static IEnumerable<Global_Industrial> _global_Industrials;
        internal static IEnumerable<Global_Industrial> GlobalIndustrials
        {
            get
            {
                if (_global_Industrials == null)
                {
                    using (var db = new DouModelContext())
                    {
                        _global_Industrials = db.GlobalIndustrial
                                            .OrderBy(a => a.Id)
                                            .ToArray();
                    }
                }
                return _global_Industrials;
            }
        }


        public static void Reset()
        {
            _global_Industrials = null;
        }
        public override IEnumerable<KeyValuePair<string, object>> GetSelectItems()
        {
            return GlobalIndustrials.Select(s => new KeyValuePair<string, object>(s.Id, s.Name));
        }
    }
}
