//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 冷媒設備
    /// </summary>
    public partial class Refrigerant_equip
    {
        /// <summary>
        /// 編號
        /// </summary>
        [Key]
        [Display(Name = "編號")]
        public string Id { get; set; }

        /// <summary>
        /// 設備名稱
        /// </summary>
        [Display(Name = "設備名稱")]
        public string Name { get; set; }

        /// <summary>
        /// 逸散率% (平均)
        /// </summary>
        [Display(Name = "逸散率% (係數)")]
        public float EscapeRate { get; set; }

        /// <summary>
        /// 最小單位數
        /// </summary>
        [Display(Name = "最小單位數")]
        public float MinValue { get; set; }

        /// <summary>
        /// 最大單位數
        /// </summary>
        [Display(Name = "最大單位數")]
        public float MaxValue { get; set; }
        /// <summary>
        /// 順序
        /// </summary>
        [Display(Name = "順序")]
        public int displayOrder { get; set; }

        /// <summary>
        /// 每一設備冷媒順序不一樣
        /// </summary>
        public List<Refrigerant_map> EquipTypeMap { set; get; }
    }

}
