//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// 冷媒種類
    /// </summary>
    public partial class Refrigerant_type
    {
        /// <summary>
        /// 編號
        /// </summary>
        [Key]
        [Display(Name = "編號")]
        public string Id { get; set; }

        /// <summary>
        /// 冷媒名稱
        /// </summary>
        [Display(Name = "冷媒名稱")]
        public string Name { get; set; }

        public decimal GWP_AR4
        {
            get { return GWP; }
        }

        /// <summary>
        /// 暖化係數
        /// </summary>
        [Display(Name = "HFCs GWP")]
        public decimal GWP { get; set; }

        [Display(Name = "HFCs GWP AR5")]
        public decimal GWP_AR5 { get; set; }

        [Display(Name = "HFCs GWP AR6")]
        public decimal GWP_AR6 { get; set; }

        /// <summary>
        /// 順序
        /// </summary>
        [Display(Name = "順序")]
        public int displayOrder { get; set; }

        //public List<Refrigerant_map> EquipTypeMap { set; get; }
    }
}
