//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using Dou.Misc.Attr;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("User_Properties")]
    public partial class User_Properties
    {
        /// <summary>
        /// 統一編號
        /// </summary>
        [Display(Name = "統一編號", Order = 0)]
        //[ColumnDef(Visible = false)]
        public string Id { get; set; }

        /// <summary>
        /// 公司名稱
        /// </summary>
        [Display(Name = "公司名稱")]
        [ColumnDef(Filter = true, FilterAssign = FilterAssignType.Contains)]
        public string Name { get; set; }

        /// <summary>
        /// 工商登記編號
        /// </summary>
        [Key]
        [Display(Name = "工商登記編號")]
        [Required]
        [ColumnDef(Filter = true, FilterAssign = FilterAssignType.Contains)]
        public string IndustryId { get; set; }

        /// <summary>
        /// 產業別
        /// </summary>
        [Display(Name = "產業別")]
        public string IndustryType { get; set; }

        /// <summary>
        /// 負責人
        /// </summary>
        [Display(Name = "負責人")]
        public string Owner { get; set; }

        /// <summary>
        /// 聯絡人
        /// </summary>
        [Display(Name = "聯絡人")]
        public string Contact { get; set; }

        /// <summary>
        /// 連絡電話
        /// </summary>
        [Display(Name = "連絡電話")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// 聯絡email
        /// </summary>
        [Display(Name = "聯絡email")]
        public string Email { get; set; }

        /// <summary>
        /// 傳真
        /// </summary>
        [Display(Name = "傳真")]
        public string Fax { get; set; }

        /// <summary>
        /// 郵遞區號
        /// </summary>
        [Display(Name = "郵遞區號")]
        public Nullable<int> AddressId { get; set; }

        /// <summary>
        /// 縣市
        /// </summary>
        [Display(Name = "縣市")]
        public string AddressCity { get; set; }

        /// <summary>
        /// 鄉鎮
        /// </summary>
        [Display(Name = "鄉鎮")]
        public string AddressCounty { get; set; }

    }
}
