//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using Dou.Misc.Attr;
    using DouHelper;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    [Table("User_Properties_Advance")]
    public partial class User_Properties_Advance
    {
        private string _Name = "";

        /// <summary>
        /// 統一編號
        /// </summary>
        [Key]
        [Display(Name = "帳號", Order = 0)]        
        [ColumnDef(Filter = true, FilterAssign = FilterAssignType.Contains)]
        public string Id { get; set; }

        /// <summary>
        /// 登入密碼
        /// </summary>
        [Display(Name = "密碼", Order = 1)]
        [ColumnDef(Visible = true , VisibleEdit = true)]
        public string Pass { get; set; }

        /// <summary>
        /// 統一編號(顯示公司名稱)
        /// </summary>
        [Display(Name = "公司名稱")]
        [ColumnDef(EditType = EditType.Select, SelectItemsClassNamespace = CFC.Models.Prj.SYS_COMPANYNameSelectItems.AssemblyQualifiedName)]
        //[ColumnDef(Filter = true, FilterAssign = FilterAssignType.Contains)]
        public string UniformNumber { get; set; }

        [Display(Name = "統一編號")]
        public string UniformNumberNo
        {
            get { return this.UniformNumber; }
        }

        /// <summary>
        /// 公司名稱(舊欄位)
        /// </summary>
        [Display(Name = "公司名稱")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public string Name { get; set; }

        /// <summary>
        /// 公司規模
        /// </summary>
        [Display(Name = "公司規模")]
        public string CompanySizeNew
        {
            get
            {
                string str = "";
                var com = SYS_COMPANYNameSelectItems.SysCompanys.Where(a => a.COMP_UNIFORM_NUMBER == this.UniformNumber).FirstOrDefault();
                if (com != null)
                    str = com.COMP_SIZE;

                return str;
            }
        }

        /// <summary>
        /// 公司規模(舊欄位)
        /// </summary>
        [Display(Name = "公司規模")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public string CompanySize { get; set; }

        /// <summary>
        /// 聯絡人
        /// </summary>
        [Display(Name = "聯絡人")]
        public string Contact { get; set; }

        [Display(Name = "職稱")]
        public string POSITION { get; set; }

        /// <summary>
        /// 連絡電話
        /// </summary>
        [Display(Name = "連絡電話")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// 聯絡email
        /// </summary>
        [Display(Name = "聯絡email")]
        public string Email { get; set; }

        /// <summary>
        /// 1.非製造業,其它製造業(ex.2,3,...99等)  修改
        /// </summary>
        [Display(Name = "行業別")]
        [ColumnDef(Visible = false, 
                EditType = EditType.Select, SelectItemsClassNamespace = CFC.GetYNGlobal_IndustrialSelectItems.AssemblyQualifiedName)]        
        public string IndustrialTypeId { get; set; }

        /// <summary>
        /// 行業別名稱(1.非製造業,其它製造業)  清單顯示
        /// </summary>
        [Display(Name = "行業別")]
        [ColumnDef(VisibleEdit = false)]
        public string IndustrialTypeName
        {
            get
            {
                string str = "";
                var v = Global_Industrial.GetAllDatasYN().Where(a => a.Id == this.IndustrialTypeId).FirstOrDefault();
                if (v != null)
                    str = v.Name;

                return str;
            }
        }

        [Display(Name = "單位性質")]
        [ColumnDef(EditType = EditType.Select, SelectItemsClassNamespace = CFC.GetUserUNIT_TYPESelectItems.AssemblyQualifiedName)]
        public string UNIT_TYPE { get; set; }

        [Display(Name = "縣市")]
        [ColumnDef(EditType = EditType.Select, SelectItemsClassNamespace = CityByNameSelectItems.AssemblyQualifiedName)]
        public string CITY { get; set; }

        [Display(Name = "鄉鎮市區")]
        [ColumnDef(EditType = EditType.Select, SelectItemsClassNamespace = TownByNameSelectItems.AssemblyQualifiedName)]
        public string DISTRICT { get; set; }

        [Display(Name = "地址")]
        public string ADDRESS { get; set; }

        /// <summary>
        /// 工商登記編號
        /// </summary>

        [Display(Name = "工商登記編號")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public string IndustryId { get; set; }

        [Display(Name = "縣市別")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public string CountyId { get; set; }

        [Display(Name = "工業園區")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public string IndustrialAreaId { get; set; }
     
        /// <summary>
        /// xxx
        /// </summary>
        [NotMapped]
        [Display(Name = "工廠")]
        public List<SYS_FACTORY> FactoryList { get; set; }

        [NotMapped]
        [Display(Name = "製造或非製造業")]
        [ColumnDef(Visible = false, VisibleEdit = false)]
        public string Manufacturing { get; set; }

        static object lockGetAllDatas = new object();
        public static IEnumerable<User_Properties_Advance> GetAllDatas(int cachetimer = 0)
        {
            if (cachetimer == 0) cachetimer = Constant.cacheTime;

            string key = "CFC.Models.Prj.User_Properties_Advance";
            var allData = DouHelper.Misc.GetCache<IEnumerable<User_Properties_Advance>>(cachetimer, key);
            lock (lockGetAllDatas)
            {
                if (allData == null)
                {
                    Dou.Models.DB.IModelEntity<User_Properties_Advance> modle = new Dou.Models.DB.ModelEntity<User_Properties_Advance>(new DouModelContext());
                    allData = modle.GetAll().OrderByDescending(a => a.Id).ToArray();

                    DouHelper.Misc.AddCache(allData, key);
                }
            }

            return allData;
        }

        public static void ResetGetAllDatas()
        {
            string key = "CFC.Models.Prj.User_Properties_Advance";
            Misc.ClearCache(key);
        }

    }

    public class Fac
    {
        public string name { get; set; }
        public string sid { get; set; }
    }
}
