//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_InputAdvance
    {
        /// <summary>
        /// 編號(流水號)
        /// </summary>
        [Display(Name = "編號")]
        public int Id { get; set; }

        /// <summary>
        /// 使用者編號
        /// </summary>
        [Display(Name = "使用者編號")]
        public string UserId { get; set; }

        /// <summary>
        /// 輸入時間
        /// </summary>
        [Display(Name = "輸入時間")]
        public System.DateTime Date { get; set; }

        /// <summary>
        /// 自產煤
        /// </summary>
        [Display(Name = "自產煤")]
        public float A1 { get; set; }

        /// <summary>
        /// 原料煤
        /// </summary>
        [Display(Name = "原料煤")]
        public float A2 { get; set; }

        /// <summary>
        /// 燃料煤
        /// </summary>
        public float A3 { get; set; }

        /// <summary>
        /// 無煙煤
        /// </summary>
        public float A4 { get; set; }

        /// <summary>
        /// 焦煤
        /// </summary>
        public float A5 { get; set; }

        /// <summary>
        /// 煙煤
        /// </summary>
        public float A6 { get; set; }

        /// <summary>
        /// 亞煙煤(發電)
        /// </summary>
        public float A7 { get; set; }

        /// <summary>
        /// 亞煙煤(其他)
        /// </summary>
        public float A8 { get; set; }

        /// <summary>
        /// 褐煤
        /// </summary>
        public float A9 { get; set; }

        /// <summary>
        /// 油頁岩
        /// </summary>
        public float A10 { get; set; }

        /// <summary>
        /// 泥煤
        /// </summary>
        public float A11 { get; set; }

        /// <summary>
        /// 煤球
        /// </summary>
        public float A12 { get; set; }

        /// <summary>
        /// 焦炭
        /// </summary>
        public float A13 { get; set; }

        /// <summary>
        /// 石油焦
        /// </summary>
        public float A14 { get; set; }

        /// <summary>
        /// 航空汽油(固定源)
        /// </summary>
        public float A15 { get; set; }

        /// <summary>
        /// 航空燃油(固定源)
        /// </summary>
        public float A16 { get; set; }

        /// <summary>
        /// 原油
        /// </summary>
        public float A17 { get; set; }

        /// <summary>
        /// 奧里油
        /// </summary>
        public float A18 { get; set; }

        /// <summary>
        /// 天然氣凝結油
        /// </summary>
        public float A19 { get; set; }

        /// <summary>
        /// 煤油(固定源)
        /// </summary>
        public float A20 { get; set; }

        /// <summary>
        /// 頁岩油
        /// </summary>
        public float A21 { get; set; }

        /// <summary>
        /// 柴油(固定源)
        /// </summary>
        public float A22 { get; set; }

        /// <summary>
        /// 車用汽油(固定源)
        /// </summary>
        public float A23 { get; set; }

        /// <summary>
        /// 蒸餘油 (燃料油)
        /// </summary>
        public float A24 { get; set; }

        /// <summary>
        /// 液化石油氣(固定源)
        /// </summary>
        public float A25 { get; set; }

        /// <summary>
        /// 石油腦
        /// </summary>
        public float A26 { get; set; }

        /// <summary>
        /// 柏油
        /// </summary>
        public float A27 { get; set; }

        /// <summary>
        /// 潤滑油(固定源)
        /// </summary>
        public float A28 { get; set; }

        /// <summary>
        /// 其他油品
        /// </summary>
        public float A29 { get; set; }

        /// <summary>
        /// 乙烷
        /// </summary>
        public float A30 { get; set; }

        /// <summary>
        /// 天然氣
        /// </summary>
        public float A31 { get; set; }

        /// <summary>
        /// 煉油氣
        /// </summary>
        public float A32 { get; set; }

        /// <summary>
        /// 焦爐氣
        /// </summary>
        public float A33 { get; set; }

        /// <summary>
        /// 高爐氣
        /// </summary>
        public float A34 { get; set; }

        /// <summary>
        /// 航空汽油(移動源)
        /// </summary>
        public float A35 { get; set; }

        /// <summary>
        /// 航空燃油(移動源)
        /// </summary>
        public float A36 { get; set; }

        /// <summary>
        /// 車用汽油(移動源)
        /// </summary>
        public float A37 { get; set; }

        /// <summary>
        /// 柴油(移動源)
        /// </summary>
        public float A38 { get; set; }

        /// <summary>
        /// 煤油(移動源)
        /// </summary>
        public float A39 { get; set; }

        /// <summary>
        /// 潤滑油(移動源)
        /// </summary>
        public float A40 { get; set; }

        /// <summary>
        /// 液化石油氣(移動源)
        /// </summary>
        public float A41 { get; set; }

        /// <summary>
        /// 液化天然氣
        /// </summary>
        public float A42 { get; set; }

        /// <summary>
        /// 電費年分
        /// </summary>
        public string elecYear { get; set; }

        /// <summary>
        /// 電費用量
        /// </summary>
        public float elecVolume { get; set; }

        /// <summary>
        /// 電冰箱
        /// </summary>
        public float CE1 { get; set; }

        /// <summary>
        /// 冷氣機
        /// </summary>
        public float CE2 { get; set; }

        /// <summary>
        /// 除濕機
        /// </summary>
        public float CE3 { get; set; }

        /// <summary>
        /// 熱泵熱水器
        /// </summary>
        public float CE4 { get; set; }

        /// <summary>
        /// 冰水機
        /// </summary>
        public float CE5 { get; set; }

        /// <summary>
        /// 冷凍機
        /// </summary>
        public float CE6 { get; set; }

        /// <summary>
        /// 冷凍乾燥機
        /// </summary>
        public float CE7 { get; set; }

        /// <summary>
        /// 熱泵系統
        /// </summary>
        public float CE8 { get; set; }

        /// <summary>
        /// 冷凍(藏)庫
        /// </summary>
        public float CE9 { get; set; }

        /// <summary>
        /// 大型冷凍(藏)庫
        /// </summary>
        public float CE10 { get; set; }

        /// <summary>
        /// 車用空調
        /// </summary>
        public float CE11 { get; set; }

        /// <summary>
        /// 冷凍物流車
        /// </summary>
        public float CE12 { get; set; }

        /// <summary>
        /// 電冰箱冷媒種類
        /// </summary>
        public string CE1_T { get; set; }

        /// <summary>
        /// 冷氣機冷媒種類
        /// </summary>
        public string CE2_T { get; set; }

        /// <summary>
        /// 除濕機冷媒種類
        /// </summary>
        public string CE3_T { get; set; }

        /// <summary>
        /// 熱泵熱水器冷媒種類
        /// </summary>
        public string CE4_T { get; set; }

        /// <summary>
        /// 冰水機冷媒種類
        /// </summary>
        public string CE5_T { get; set; }

        /// <summary>
        /// 冷凍機冷媒種類
        /// </summary>
        public string CE6_T { get; set; }

        /// <summary>
        /// 冷凍乾燥機冷媒種類
        /// </summary>
        public string CE7_T { get; set; }

        /// <summary>
        /// 熱泵系統冷媒種類
        /// </summary>
        public string CE8_T { get; set; }

        /// <summary>
        /// 冷凍(藏)庫冷媒種類
        /// </summary>
        public string CE9_T { get; set; }

        /// <summary>
        /// 大型冷凍(藏)庫冷媒種類
        /// </summary>
        public string CE10_T { get; set; }

        /// <summary>
        /// 車用空調冷媒種類
        /// </summary>
        public string CE11_T { get; set; }

        /// <summary>
        /// 冷凍物流車冷媒種類
        /// </summary>
        public string CE12_T { get; set; }

        /// <summary>
        /// 蒸氣用量
        /// </summary>
        public float F1 { get; set; }

        /// <summary>
        /// 蒸氣係數，自行填報
        /// </summary>
        public decimal F1_T { get; set; }

    }
}
