//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Prj
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public class User_Projects : ProjectProperties
    {
        /// <summary>
        /// 使用者編號
        /// </summary>
        [Display(Name = "使用者編號")]
        [Key]
        [Column(Order =0)]
        public override string UserID { get; set; }

        [Key]
        [Column(Order = 1)]
        public override string ProjectIndustrialID { get; set; }//專案場登
    }

    public class ProjectProperties {

        public virtual string UserID { get; set; }

        public virtual string ProjectIndustrialID { get; set; }//專案場登

        // 專案需求
        public string ProjectAddress { get; set; }//專案地址
        public string ProjectCity { get; set; }//專案縣市
        public string ProjectIndustrialType { get; set; }//專案行業別
    }
}
