//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFC.Models.Joined.Calculate
{
    using CFC.Models.Prj;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 電力計算
    /// </summary>
    public partial class UserInput_Advance
    {
        public User_InputAdvance basicInput { get; set; }

        /*
          基本與原先的UserInput相同
          新增 
            1. 逸散氣體的 一對多
            2. 特殊製程的 一對多
         */

        public List<Escape_volume> escapeVolumes = new List<Escape_volume>();

        public List<Specific_volume> specificVolumes = new List<Specific_volume>();
    }
}
