--Select FACTORY_CITY, FACTORY_DISTRICT, FACTORY_ADDRESS,
--       ISNULL(FACTORY_CITY, '') AS FACTORY_CITY, 
--       ISNULL(FACTORY_DISTRICT, '') AS FACTORY_DISTRICT, 
--	   ISNULL(FACTORY_ADDRESS , '') AS FACTORY_ADDRESS
--from SYS_FACTORY

Update SYS_FACTORY
Set FACTORY_CITY = ISNULL(FACTORY_CITY, ''),
    FACTORY_DISTRICT = ISNULL(FACTORY_DISTRICT, ''),
	FACTORY_ADDRESS = ISNULL(FACTORY_ADDRESS , '')
